---
title: "Day 1"
author: "Amy Heather"
date: "2024-07-26"
categories: [setup]
bibliography: ../../../quarto_site/references.bib
---

::: {.callout-note}

Set-up repository and upload materials. Total time used: 0h 32m (1.3%)

:::

## 15.58-16.03, 16.21-16.30: Set-up repository

* Create repository from template
* Set up environment
* Modified template files:
    * `README.md`
    * quarto site `index.qmd`
    * `CITATION.cff`
    * `_quarto.yml`
* Set up site on GitHub pages (`quarto publish gh-pages`)

## 16.36-16.41: Upload code and update license

Model code is available at: <https://github.com/mikesweeting/AAA_DES_model>

It is available under an LGPL-3.0 license, so I updated this repository to use the same license (GNU LESSER GENERAL PUBLIC LICENSE Version 3). [This license requires](https://fossa.com/blog/open-source-software-licenses-101-lgpl-license/):

* Copy of full license and original copyright notice
* Include source code when distribute derivative work
* License derivative work under same license

## 16.43-16.56: Upload journal article

The article is published with PLoS ONE and has a permissive copyright statement:

> "Copyright: © 2021 Kim et al. This is an open access article distributed under the terms of the Creative Commons Attribution License, which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited."

<https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0253327>

Hence, uploaded article, figures, tables and supplementary materials to `original_study/`. Converted `.tif` files to `.png` (e.g. `convert sup3.tif sup3.png`). Converted `.docx` to `.pdf` (`libreoffice --headless --convert-to pdf sup1.docx --outdir sup1.pdf`).

Amended `study_publication.qmd` to display these.

Add the study to `references.bib`.

## Timings

```{python}
import sys
sys.path.append('../')
from timings import calculate_times

# Minutes used prior to today
used_to_date = 0

# Times from today
times = [
    ('15.58', '16.03'),
    ('16.21', '16.30'),
    ('16.36', '16.41'),
    ('16.43', '16.56')]

calculate_times(used_to_date, times)
```