---
title: "Process model results to generate results in article"
author: "Amy Heather"
---

This script assumes you have already run the scenarios in `models/` and saved those results to `.csv` files which we here then process to generate the results from the paper.

## Set-up

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r}
# Path to output folder
outputs = "../output"

# Paths to output files
paths <- list(
  y65_s1= file.path(outputs, "output_65yo_scen1_1mil.csv"),
  tab2 = file.path(outputs, "tab2.csv"),
  fig1 = file.path(outputs, "fig1.png")
)
```

```{r}
# Import files
y65_s1 <- read.csv(paths$y65_s1)

# Preview 65 year old scenario 1 dataframe with 1 million people
head(y65_s1, 3)
```

## Table 2

```{r}
make_tab2 <- function(df, n_person) {
  #' Create table 2 from the article
  #' 
  #' Create table with a count of excess deaths and excess emergency operations
  #' with increasing delays in the simulation.
  #' 
  #' @param df Dataframe with results from the model
  #' @param n_person Integer - number of people in simulation
  #' @return tab2 Dataframe with excess deaths and emergency operations
  #' @examples
  #' make_tab2(y65_s1_1m, 1000000)

  full_tab2 <- df %>%
    # Sort by length of delay (so first row is 0 delay)
    arrange(delayscr) %>%
    # Calculate the total number of emergency operations
    mutate(total_emer = emerevar + emeropen) %>%
    select(delayscr, aaadead, total_emer) %>%
    # Scale to number of deaths if population size was 279,798
    mutate(scaled_dead = round(279798*(aaadead/n_person)),
           scaled_emer = round(279798*(total_emer/n_person))) %>%
    # Calculate excess (compare to time 0, but set negative to 0)
    mutate(excess_dead = pmax(scaled_dead - first(scaled_dead), 0),
           excess_emer = pmax(scaled_emer - first(scaled_emer), 0))

  # Filter and format to match paper
  tab2 <- full_tab2 %>%
    # Just keep a subset of results
    filter(delayscr %in% c(0.5, 1, 2, 3, 4, 5)) %>%
    # Convert time from years to months
    mutate(months = paste0(delayscr*12, "m")) %>%
    select(months, excess_dead, excess_emer)

  return(tab2)
}
```

Simulation 65yo scen1 with 1,000,000 people

```{r}
tab2_1m <- make_tab2(y65_s1, 1000000)

write.csv(tab2_1m, paths$tab2, row.names=FALSE)

tab2_1m
```

## Figure 1

Process results from model into a dataframe to use for plotting.

```{r}
fig1_df <- y65_s1 %>%
  # Sort by length of delay (so first row is 0 delay)
  arrange(delayscr) %>%
  # Calculate the total number of emergency and elective operations
  mutate(total_emer = emerevar + emeropen,
         total_elec = elecevar + elecopen) %>%
  # Keep relevant columns
  select(delayscr, aaadead, total_elec, total_emer, rupt) %>%
  # Drop result from 0.25 months (not included in plot)
  filter(delayscr != 0.25) %>%
  # Calculate percentage change from timepoint 0
  mutate(pct_dead = (aaadead - first(aaadead)) / first(aaadead) * 100,
         pct_elec = (total_elec - first(total_elec)) / first(total_elec) * 100,
         pct_emer = (total_emer - first(total_emer)) / first(total_emer) * 100,
         pct_rupt = (rupt - first(rupt)) / first(rupt) * 100) %>%
  # Keep relevant columns
  select(delayscr, starts_with("pct_"))

fig1_df
```

Melt the dataframe into long format for then creating the line plot.

```{r}
# Define labels
fig1_lab = list(pct_dead = "AAA deaths",
                pct_elec = "Elective operations",
                pct_emer = "Emergency operations",
                pct_rupt = "Ruptures")

# Melt dataframe from wide to long and add labels
fig1_long <- fig1_df %>%
  pivot_longer(-delayscr) %>%
  mutate(label = recode(name, !!!fig1_lab, .default = NA_character_))

fig1_long
```

```{r}
ggplot(fig1_long, aes(x=delayscr, y=value, color=label)) +
  geom_line() +
  geom_point() +
  labs(x="Delay in initial invitation (years)",
       y="Percentage change in outcome",
       color="Outcome") +
  scale_y_continuous(limits = c(-10, 10),
                     breaks = seq(-10, 10, 2)) +
  geom_hline(yintercept=0) +
  theme_bw()

ggsave(paths$fig1)
```

