---
title: "STARS framework"
bibliography: ../quarto_site/references.bib
---

<!-- TODO: Remove this warning once completed assessment -->
**Please note: This is a template page and has not yet been completed**

This page evaluates the extent to which the original study meets the recommendations from the STARS framework for the sharing of code and associated materials from discrete-event simulation models (@monks_towards_2024).

Of the **8** essential STARS components:

<!-- TODO: Add counts from evaluation -->
* **X** were met fully (✅)
* **X** was met partially (🟡)
* **X** was not met (❌)

Of the **5** optional STARS components:

<!-- TODO: Add counts from evaluation -->
* **X** was met fully (✅)
* **X** were not met (❌)

<!-- TODO: Fill in the table. Options are ✅ Fully, 🟡 Partially, or ❌ Not met -->
| Component | Description | Met by study? | Evidence/location |
| - | - | :-: | - |
| **Essential components** |
| Open license | Free and open-source software (FOSS) license (e.g. MIT, GNU Public License (GPL)) | ✅ Fully | LGPL-3.0 |
| Dependency management | Specify software libraries, version numbers and sources (e.g. dependency management tools like virtualenv, conda, poetry) | 🟡 Partially | Includes installation instructions/commandas at start of scripts, listing the required packages, but not versions |
| FOSS model | Coded in FOSS language (e.g. R, Julia, Python) | ✅ Fully | R |
| Minimum documentation | Minimal instructions (e.g. in README) that overview (a) what model does, (b) how to install and run model to obtain results, and (c) how to vary parameters to run new experiments | ✅ Fully | Includes a README which describe the repository structure (e.g. where input parameters are located, where script is located), which directs to an example file that explains how to run the model and vary inputs |
| ORCID | ORCID for each study author | ❌ Not met | - |
| Citation information | Instructions on how to cite the research artefact (e.g. CITATION.cff file) | ❌ Not met | - |
| Remote code repository | Code available in a remote code repository (e.g. GitHub, GitLab, BitBucket) | ✅ Fully | <https://github.com/mikesweeting/AAA_DES_model> |
| Open science archive | Code stored in an open science archive with FORCE11 compliant citation and guaranteed persistance of digital artefacts (e.g. Figshare, Zenodo, the Open Science Framework (OSF), and the Computational Modeling in the Social and Ecological Sciences Network (CoMSES Net)) | ❌ Not met | - |
| **Optional components** |
| Enhanced documentation | Open and high quality documentation on how the model is implemented and works  (e.g. via notebooks and markdown files, brought together using software like Quarto and Jupyter Book). Suggested content includes:<br>• Plain english summary of project and model<br>• Clarifying license<br>• Citation instructions<br>• Contribution instructions<br>• Model installation instructions<br>• Structured code walk through of model<br>• Documentation of modelling cycle using TRACE<br>• Annotated simulation reporting guidelines<br>• Clear description of model validation including its intended purpose | ❌ Not met | - |
| Documentation hosting | Host documentation (e.g. with GitHub pages, GitLab pages, BitBucket Cloud, Quarto Pub) | ❌ Not met | - |
| Online coding environment | Provide an online environment where users can run and change code (e.g. BinderHub, Google Colaboratory, Deepnote) | ❌ Not met | - |
| Model interface | Provide web application interface to the model so it is accessible to less technical simulation users | ❌ Not met | - |
| Web app hosting | Host web app online (e.g. Streamlit Community Cloud, ShinyApps hosting) | ❌ Not met | - |
: {tbl-colwidths="[20, 35, 20, 25]"}
